[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "python_template"
version = "0.0.1"

[tool.pytest.ini_options]
addopts = [
  "--import-mode=importlib",
]
